@baseUrl = http://localhost:3000/
@token_login = {{login.response.body.token}}
@user_id = {{login.response.body.user.id}}
@first_task_id = 94715252-461b-4836-8a57-a477870e5d99

### Auth

# @name login
POST {{baseUrl}}api/auth/login
Content-Type: application/json

{
    "email": "filipe@email.com",
    "password": "password"
}

### 

# @name register
POST {{baseUrl}}api/auth/register
Content-Type: application/json

{
    "email": "filipe@email.com",
    "username": "filipe",
    "password": "password"
}

### 

# @name refresh
POST {{baseUrl}}api/auth/refresh
Content-Type: application/json
Authorization: Bearer {{token_login}}
Cookie: refresh_token=''

### Tasks

# @name create_task
POST {{baseUrl}}api/tasks
Content-Type: application/json
Authorization: Bearer {{token_login}}

{
    "titulo": "Teste",
    "descricao": "string",
    "prazo": "2025-12-14T00:25:11.980Z",
    "prioridade": "urgent",
    "status": "review",
    "user_id": "{{user_id}}"
}

###

# @name get_all_tasks
GET {{baseUrl}}api/tasks
Content-Type: application/json
Authorization: Bearer {{token_login}}

###

# @name get_one_task_by_id
GET {{baseUrl}}api/tasks/{{first_task_id}}
Content-Type: application/json
Authorization: Bearer {{token_login}}

###

# @name updateTask
PUT {{baseUrl}}api/tasks/{{first_task_id}}
Content-Type: application/json
Authorization: Bearer {{token_login}}

{
    "titulo": "Teste",
    "descricao": "string",
    "prazo": "2025-12-14T00:25:11.980Z",
    "prioridade": "urgent",
    "status": "review",
    "user_id": "{{user_id}}"
}

###

# @name deleteTask
DELETE {{baseUrl}}api/tasks/{{first_task_id}}
Content-Type: application/json
Authorization: Bearer {{token_login}}

###

# @name createComment
POST {{baseUrl}}api/tasks/{{first_task_id}}/comments
Content-Type: application/json
Authorization: Bearer {{token_login}}

{
    "comment_text":"Comentário teste"
}

###

# @name getComments
GET {{baseUrl}}api/tasks/{{first_task_id}}/comments
Content-Type: application/json
Authorization: Bearer {{token_login}}